service: aws-python-http-api
frameworkVersion: 2

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::pontte-upload-docs-staging"

functions:
  textract:
    handler: handler.textract
    events:
      - httpApi:
          path: /
          method: post
